<Type Name="CXErrorCodeIncomingCallError" FullName="CallKit.CXErrorCodeIncomingCallError">
  <TypeSignature Language="C#" Value="public enum CXErrorCodeIncomingCallError" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed CXErrorCodeIncomingCallError extends System.Enum" />
  <AssemblyInfo>
    <AssemblyName>Xamarin.iOS</AssemblyName>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Attributes>
    <Attribute>
      <AttributeName>ObjCRuntime.Introduced(ObjCRuntime.PlatformName.iOS, 10, 0, ObjCRuntime.PlatformArchitecture.None, null)</AttributeName>
    </Attribute>
    <Attribute>
      <AttributeName>ObjCRuntime.Native</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>Enumerates incoming call errors.</summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName="CallUuidAlreadyExists">
      <MemberSignature Language="C#" Value="CallUuidAlreadyExists" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype CallKit.CXErrorCodeIncomingCallError CallUuidAlreadyExists = int64(2)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
        <AssemblyName>Xamarin.iOS</AssemblyName>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>CallKit.CXErrorCodeIncomingCallError</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>The UUID for the call already exists.</summary>
      </Docs>
    </Member>
    <Member MemberName="FilteredByBlockList">
      <MemberSignature Language="C#" Value="FilteredByBlockList" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype CallKit.CXErrorCodeIncomingCallError FilteredByBlockList = int64(4)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
        <AssemblyName>Xamarin.iOS</AssemblyName>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>CallKit.CXErrorCodeIncomingCallError</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>The caller is blocked.</summary>
      </Docs>
    </Member>
    <Member MemberName="FilteredByDoNotDisturb">
      <MemberSignature Language="C#" Value="FilteredByDoNotDisturb" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype CallKit.CXErrorCodeIncomingCallError FilteredByDoNotDisturb = int64(3)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
        <AssemblyName>Xamarin.iOS</AssemblyName>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>CallKit.CXErrorCodeIncomingCallError</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>The device is in Do Not Disturb mode.</summary>
      </Docs>
    </Member>
    <Member MemberName="Unentitled">
      <MemberSignature Language="C#" Value="Unentitled" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype CallKit.CXErrorCodeIncomingCallError Unentitled = int64(1)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
        <AssemblyName>Xamarin.iOS</AssemblyName>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>CallKit.CXErrorCodeIncomingCallError</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="Unknown">
      <MemberSignature Language="C#" Value="Unknown" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype CallKit.CXErrorCodeIncomingCallError Unknown = int64(0)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
        <AssemblyName>Xamarin.iOS</AssemblyName>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>CallKit.CXErrorCodeIncomingCallError</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>An unknown error occured.</summary>
      </Docs>
    </Member>
  </Members>
</Type>
